#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
 sudo yabai --load-sa
 yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
 
# yabai -m config external_bar all:26:0

# global settings
yabai -m config mouse_follows_focus          on 
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on 
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          6
yabai -m config window_border_radius         0
yabai -m config active_window_border_color   0xff00ff00
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               6 
yabai -m config left_padding                 38
yabai -m config right_padding                38
yabai -m config window_gap                   38

# Space labels
yabai -m space 1 --label "1"
yabai -m space 2 --label "2"
yabai -m space 3 --label "3"
yabai -m space 4 --label "4"
yabai -m space 5 --label "5"
yabai -m space 6 --label "6"

# Space config
yabai -m config --space 5 layout float

# Unmanaged
yabai -m rule --add app="^System Preferences$"  manage=off border=off
yabai -m rule --add app="Finder"                manage=off border=off
yabai -m rule --add app="QuickTime Player"      manage=off border=off
#yabai -m rule --add app="Messages"              manage=off border=off
#yabai -m rule --add app="WhatsApp"              manage=off border=off
yabai -m rule --add app="Music"                 manage=off border=off
yabai -m rule --add app="VirtualBox"            manage=off border=off
yabai -m rule --add app="The Unarchiver"        manage=off border=off
 

# Primary
#yabai -m rule --add app="Safari"                space=1

# Communication
#yabai -m rule --add app="Google Chrome"         space=2

# Tools
#yabai -m rule --add app="Terminal"              space=3

# Media
#yabai -m rule --add app="VLC"                   space=4
#yabai -m rule --add app="Spotify"               space=4

# Social
#yabai -m rule --add app="Discord"               space=5

# Floating
#yabai -m rule --add app="^System Preferences$"  space=6
#yabai -m rule --add app="ScreenFlow 9"          space=6

# add the following to the end of your yabairc to have it launch automatically when yabai starts.
# make sure the limelight binary is added somewhere in your $PATH

# kill any existing limelight process if one exists, before we launch a new one
#killall limelight &> /dev/null
#limelight &> /dev/null &

echo "yabai configuration loaded.."
